### ISSUE TITLE
In-game menu

### ISSUE THREAD

**Issue by Victor1337** [Jire/Abendigo#100]
My in-game menu doesn't appear. Any sollutions?

**Comment by Jire** [comment]
There is no in-game menu.

**Comment by Intrepidus99** [comment]
@Victor1337  The controller only appears if the game is in either windowed or fullscreen windowed.

**Comment by Victor1337** [comment]
Ok, so there is no in-game menu. The next thing I want to ask is how do I enable "rage hack" as I've seen in other videos? There's a list to the left of the screen where you can choose want you want to toggle on or off.

**Comment by Intrepidus99** [comment]
The list is the controller i was talking about, and there is no native rage plugin for abendigo, but there are other plugins you can enable in the abendigo.kt file

**Comment by Victor1337** [comment]
Okay, thank you so much! :+1:
