### ISSUE TITLE
Can I use old ESP?

### ISSUE THREAD

**Issue by punkjj** [Jire/Abendigo#11]
Actually , I dont like the new update (FOV Aim and RCS) So, Im using old abendigo , cus I configured it my way .. I noticed a recent change in ESP Plugin .. Is old one detected ?

**Comment by Jire** [comment]
@punkjj If you want to use old aim system just disable default ones (RCS and FOV) and enable the old aim plugins (aim assist and spray assist).

Old ESP is not detected, but the new one is very much improved and I recommend it.

Also, you mentioned that you don't like the new FOV/RCS, can you tell me what problems you had and what you think could be improved?
