### ISSUE TITLE
How to make aim a little more powerfull ? Like always HS in USP ? 

### ISSUE THREAD

**Issue by punkjj** [Jire/Abendigo#12]
Make a new plugin file if possible cus I the old plugin is good for other weapons except USP

**Comment by punkjj** [comment]
I tried to make a new aimassist  file and put bones 6 but still it doesn't give HS .. I wont something that always gives a HS it can be called "Rage-Bot for Pistols" Please help ...

**Comment by Jire** [comment]
Change the smoothing and try lowering the duration to 16.

**Comment by uhFocuz** [comment]
Please don't teach them this. The game is already worse by the day lmao, My custom rage bot is the only thing giving me a change. I liked when you planned not to support this :)
