### ISSUE TITLE
Explain BoneTriggerPlugin and FOVAim (No Knowledge at all)

### ISSUE THREAD

**Issue by punkjj** [Jire/Abendigo#13]
What is Bonetriggerplugin ? The name suggests that it will shoot when the crosshair is on a certain bone like 6 ... But the FOV Aim ? Which is better ? Aimassist or FOV ?

**Comment by Jire** [comment]
You're right on the money with your bone trigger description.

I recommend FOV because it's more powerful, easier to get more kills.
