### ISSUE TITLE
Will this be ever detected or anytime soon

### ISSUE THREAD

**Issue by benjaminseng990** [Jire/Abendigo#15]
1.Will i get # VAC BAN on prime matchmaking
2.Will i get # VAC BAN in a vac wave
3.Will this be # # VAC anytime soon

**Comment by QWp6t** [comment]
1. yes
2. yes
3. yes

You should always assume you will get caught.

**Comment by Jire** [comment]
We've been undetected for about 8 months but there is always a risk for ban.
