### ISSUE TITLE
Enable/disable/changing plugins

### ISSUE THREAD

**Issue by LoneLyyy** [Jire/Abendigo#2]
I was trying to modify the plugins and enable/disable some of them and the hack doesnt save the changes

**Comment by Jire** [comment]
After you change any compiled-language source code, you need to recompile and rebuild. You can do this by running the _build.bat_ file. :)

**Comment by LoneLyyy** [comment]
Failed to rebuild

**Comment by Jire** [comment]
@LoneLyyy Then you have errors in your source code. You need to fix these errors. If you're inexperienced, you can try starting from scratch.

**Comment by Jire** [comment]
The controller is ready! :smiley:

You can build it the same way as the driver. Remember to run the driver first, then the controller. Enjoy!! https://github.com/Jire/Abendigo-Controller
