### ISSUE TITLE
Error with lines

### ISSUE THREAD

**Issue by benjaminseng990** [Jire/Abendigo#20]
Error:(34, 24) Kotlin: Type mismatch: inferred type is Double but Int was expected
Error:(34, 35) Kotlin: Type mismatch: inferred type is Double but Int was expected
Error:(35, 16) Kotlin: Type mismatch: inferred type is Double but Int was expected
Error:(36, 20) Kotlin: Type mismatch: inferred type is Double but Int was expected

**Comment by benjaminseng990** [comment]
Error:(34, 24) Kotlin: Type mismatch: inferred type is Double but Int was expected
Error:(34, 35) Kotlin: Type mismatch: inferred type is Double but Int was expected
Error:(35, 16) Kotlin: Type mismatch: inferred type is Double but Int was expected
Error:(36, 20) Kotlin: Type mismatch: inferred type is Double but Int was expected

**Comment by Jire** [comment]
Have you updated your Kotlin to the latest version (_1.0.3_)?

**Comment by Jire** [comment]
I'm assuming a loss of interest or your problem has been fixed. Please re-open the issue if that is not the case.
