### ISSUE TITLE
dont work for me 

### ISSUE THREAD

**Issue by imjins** [Jire/Abendigo#22]
i use this cheat 2 days ago and it work perfect but now nothing work i only see weapon with glow when some 1 die but thats all (sorry for my bad english) i hope some one can help me

**Comment by Jire** [comment]
Has your problem been fixed? Have you tried restarting CS:GO or the cheat?

**Comment by imjins** [comment]
nope :( i try to re install the cheat but now nothing work

**Comment by Jire** [comment]
Could you leave your Skype here so we could talk in private?

**Comment by imjins** [comment]
sure is zxsick
