### ISSUE TITLE
What does this mean?

### ISSUE THREAD

**Issue by benjaminseng990** [Jire/Abendigo#24]
AimAssistPlugin.kt

line 19,20

	private const val MIN_ELAPSED = ?
	private const val MAX_ELAPSED = ?

**Comment by Jire** [comment]
That's the range of duration (in milliseconds) between the "bursts" of aim assistance.

**Comment by benjaminseng990** [comment]
So how do u make it more overpowered?
Can u suggest ?

**Comment by Jire** [comment]
@benjaminseng990 If you lower the durations it will make it stronger. Make sure that `MIN_ELAPSED` is less than `MAX_ELAPSED`. :+1:
