### ISSUE TITLE
Need a Menu or Hotkeys to enable/disabe Plugins :/ 

### ISSUE THREAD

**Issue by punkjj** [Jire/Abendigo#3]
Please add menu  or hotkeys to enable/disable Plugins...
I saw some old videos about this project and there was a menu + GUI
But Here I cant find anything Im just a newbie donno anything about Coding and english :P

**Comment by punkjj** [comment]
@Jire  Please help make a menu or something and what you just updated O.o have to download it again ?

**Comment by Jire** [comment]
I am working to add hotkeys and a menu.

**Comment by punkjj** [comment]
OMG Thank you very much

**Comment by Jire** [comment]
@punkjj There is going to be a protocol to control Abendigo. I am developing the official controller client here: https://github.com/Jire/Abendigo-Controller

**Comment by punkjj** [comment]
@Jire Can I try that ? What I have to do ? And can you add console commands so that I can make my own scripts :cactus:

**Comment by punkjj** [comment]
@Jire Add a Triggerbot for Shotguns ? :+1:

**Comment by Jire** [comment]
The controller is ready! :smiley:

You can build it the same way as the driver. Remember to run the driver first, then the controller. Enjoy!! https://github.com/Jire/Abendigo-Controller
