### ISSUE TITLE
Abendigo cmd window no longer alerts that the cheat is working.

### ISSUE THREAD

**Issue by dontbbad** [Jire/Abendigo#32]
![86fbe3ec-08e4-42f9-ad07-408b96127a07](https://cloud.githubusercontent.com/assets/20633231/17194302/2c7ff516-540c-11e6-8d3a-f56a3b84f732.jpg)

A couple versions ago abendigo would display in the command promt window (shown in the picture) that it is injected properly. Now with the window being blank it is hard to tell as i do not run the cheat with walls, so there is no reliable way to see if it is working.

**Comment by Jire** [comment]
You can enable debug mode and it will print :smile:

Just set `DEBUG` to `true` in `Abendigo.kt`
