### ISSUE TITLE
Spray Assist and Aim assist

### ISSUE THREAD

**Issue by dontbbad** [Jire/Abendigo#33]
With both of them enabled and FOV aim disabled, neither of them work, they worked in the last version tho. Before bone trigger

**Comment by Jire** [comment]
Fixed in https://github.com/Jire/Abendigo/commit/10aa040e7efdc117bedb8c68b9d69ce60c54ea2d and https://github.com/Jire/Abendigo/commit/e8c5c9f2262e0244487fc21899084143526b40ab :grinning:
