### ISSUE TITLE
Please Fix BoneTriggerPlugin

### ISSUE THREAD

**Issue by punkjj** [Jire/Abendigo#38]
@Jire  Please Fix the BoneTriggerPlugin, It Shoots when the enemy is behind a wall , I tried to replace some lines from the ShotgunTriggerBot and made it happen but now its not working after the Arrowhead update :-1:

**Comment by punkjj** [comment]
@Jire ^^

**Comment by Jire** [comment]
Working on this 👍

**Comment by Jire** [comment]
Fixed https://github.com/Jire/Abendigo/commit/3fce4846e27de0b6392d5d376468421c82dd3ba0
