### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by mattdeveluk** [Jire/Abendigo#39]
Hello,

I am trying to compile Abendigo, but I am still getting this error.

`ERROR: JAVA_HOME is set to an invalid directory: C:\Users\xxx\AppData\Local\Programs\Eclipse Che\eclipse-che-4.0.0-RC12\tools\jre\

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.`

**Comment by Jire** [comment]
Install the JDK: http://www.oracle.com/technetwork/java/javase/downloads/index.html

**Comment by mattdeveluk** [comment]
Thanks, already solved that issue. Great tool, thank you for what you do, you do it great.
