### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by AntoninataRiech** [Jire/Abendigo#4]
Linux tut?

**Comment by Jire** [comment]
Kotmem works on Linux, but you need to roll your own offset scanning or force them to certain offsets.

**Comment by The5heepDev** [comment]
@Jire Do you, by chance, have the offsets?

**Comment by Jire** [comment]
@The5eepDev Unfortunately haven't looked much into getting them but this tutorial should help a ton: https://youtu.be/rh1Rajh5vbk

**Comment by The5heepDev** [comment]
@Jire IDA (free) is only for 32 bit. Is there a 64bit debugger that's free?

**Comment by Jire** [comment]
@The5heepDev You could use the trial version for 30 days :grinning:

**Comment by The5heepDev** [comment]
@Jire Ok, cool!
