### ISSUE TITLE
Aimbot spotting late.

### ISSUE THREAD

**Issue by hairline01** [Jire/Abendigo#40]
The fov aim spots enemys really late. e.x. when i walk around the corner holding the force aim key the aimbot takes atleast 1 second to register them and finally lock to them. Hope this is fixed in the new cheat. :)

**Comment by Jire** [comment]
It's an inherent problem of using `m_bIsSpotted` to check if the enemies are visible. My advice is to use crosshair-based target selection, which aim assist and spray assist use, as opposed to FOV.
