### ISSUE TITLE
Question: Assign weapon type to FOVaim

### ISSUE THREAD

**Issue by NanoHunter** [Jire/Abendigo#41]
I'm just starting to learn programming, so please be patient with me if you can help me^^

I want to edit this code:
private const val AIM_KEY = 1 /* left click */
	private const val FORCE_AIM_KEY = 6 
	private const val FORCE_AIM_ENHANCEMENT = 3F/* set to 1.0F for no enhancement */

	private const val LOCK_FOV = 4
	private const val UNLOCK_FOV = LOCK_FOV * 3
	private const val NEVER_STICK = true

	private const val SMOOTHING_MIN = 1F
	private const val SMOOTHING_MAX = 3F

	private const val JUMP_REDUCTION = 0.7F

	private val TARGET_BONES = arrayOf(Bones.NECK, Bones.HEAD, Bones.NECK, Bones.UPPER_CHEST)
	private const val CHANGE_BONE_CHANCE = 7

	private var target: Player? = null
	private var targetBone = newTargetBone()

	private val aim = Vector(0F, 0F, 0F)

My problem is, that I want the target bones to be assigned to a weapon category.
private val TARGET_BONES = arrayOf(Bones.NECK, Bones.HEAD, Bones.NECK, Bones.UPPER_CHEST) for automatic weapons and target bone head as only bone for pistols, to prevent it from bouncing up and down.
I was thinking of simply looping it, but when trying to implement it I got error after error ^^
Some help in form of edited code and an explanation of why and how it works would be awesome.

**Comment by punkjj** [comment]
idk about this but after today's update every aim related thing stopped working..

**Comment by NanoHunter** [comment]
When using a smoothing of 1F-2F it actually works fine for me. Using only FOV + Spray assist. They even work well together with that smoothing value.

**Comment by NanoHunter** [comment]
@Jire Do you have some time to spare and help me? D

**Comment by Jire** [comment]
@NanoHunter I think it's better left as a feature of the new cheat than to implement weapon profiles into Abendigo. Yes it can be done, but I don't have the time right now. 😞

**Comment by punkjj** [comment]
When will be the new cheat released ? Update us please @Jire
