### ISSUE TITLE
Disable RCS with pistols?

### ISSUE THREAD

**Issue by Shikkichu** [Jire/Abendigo#43]
RCS keeps pulling down for me with pistols, will there be future updates to change this?
I'm too lazy to do it myself ;w;

**Comment by Jire** [comment]
RCS only works for automatic weapons. Do you mean FOV aim?

**Comment by Shikkichu** [comment]
When I use a pistol it like makes my crosshair go down with just RCS, everything else is commented out.

**Comment by Jire** [comment]
Not really possible: https://github.com/Jire/Abendigo/blob/master/src/main/kotlin/org/abendigo/plugin/csgo/RCSPlugin.kt#L25

Are you using an old version, perhaps?

**Comment by Risitosv** [comment]
Did you change the "weapon ID"?.
https://github.com/Jire/Abendigo/commit/06562defad4d1b8ca16d2915793398cb481ee732

**Comment by Shikkichu** [comment]
I left it all default, I only have rcs uncommented, the src is the same as the one you posted.
It's doing the same with shotguns, forcing my mouse movement down.

https://www.youtube.com/watch?v=Bya-EAfdX9I

**Comment by Jire** [comment]
@Shikkichu I've tested just now and can confirm RCS does nothing with non-automatic weapons. Are you sure you have the latest commit?

**Comment by Shikkichu** [comment]
Just redownloaded 1.95b

Trying to run as admin now to see if that fixes and I get
build.bat is not recognized as an internal or external command

Running as a normal user makes it all work, but the pistols and shotguns are still all wonky, am I missing something?

**Comment by Jire** [comment]
Download the latest snapshot (commit) rather than release.

**Comment by Shikkichu** [comment]
Wonderful, thank you!

**Comment by Jire** [comment]
You're very welcome :smile:
