### ISSUE TITLE
About AimAssist.kt

### ISSUE THREAD

**Issue by benjaminseng990** [Jire/Abendigo#44]
How to make 

line 16,17
private const val SMOOTHING_MIN = ?F
private const val SMOOTHING_MAX = ?F

STRONGER?

**Comment by Jire** [comment]
Increasing the value makes it stronger. Decreasing the values makes it weaker.

**Comment by benjaminseng990** [comment]
Is it like 

private const val SMOOTHING_MIN = 100F
private const val SMOOTHING_MAX = 100F
STRONGER
-----------------------------------------------------------------------------------------------------------------
private const val SMOOTHING_MIN = 1F
private const val SMOOTHING_MAX = 1F
WEAKER

**Comment by Jire** [comment]
Yes, but the range is 0F (weakest) to 40F (strongest) 😀

**Comment by benjaminseng990** [comment]
Oh, no wonder i set higher than that last time then i was clueless that nothing happen
