### ISSUE TITLE
Can you add some new features?

### ISSUE THREAD

**Issue by punkjj** [Jire/Abendigo#5]
Jire can you add some new features ? 
Like fix radar , put hotkeys , and is it possible to get console commands of the hack ? like if we put "@esp 1" in console then ESP turns on like that ? with a prefix ?

**Comment by Jire** [comment]
The controller is ready! :smiley:

You can build it the same way as the driver. Remember to run the driver first, then the controller. Enjoy!! https://github.com/Jire/Abendigo-Controller

**Comment by Jire** [comment]
If I were to add radar, it must be in an external overlay. There are no plans right now to add radar nor console commands. Hotkeys have been added to our official controller.
