### ISSUE TITLE
What do this mean

### ISSUE THREAD

**Issue by benjaminseng990** [Jire/Abendigo#50]
FOVAIM
private const val UNLOCK_FOV = LOCK_FOV * 
How to make it better

**Comment by Jire** [comment]
`UNLOCK_FOV` is the maximum amount of FOV before the aimbot will stop "locking on" to an enemy. `LOCK_FOV` is the minimum amount of FOV before the aimbot will _start_ "locking on" to an enemy.

So... if your lock is 35, and your unlock is 70 (lock * 2): Once an enemy is within 35 FOV it will start "locking on" to them, but if you don't guide your crosshair enough, or pull away from them, once the crosshair is out of 70 FOV it will "unlock".. therefore no longer assisting you.
