### ISSUE TITLE
Strange Exception?

### ISSUE THREAD

**Issue by noobtra** [Jire/Abendigo#54]
https://s.put.re/a2ctULJ.png

Happens everytime I execute run.bat, and because of it, seems like I can't use any plugins at all.

**Comment by punkjj** [comment]
Are you using abendigo first time?  Or it just appeared suddenly?

**Comment by noobtra** [comment]
This is my first time using the open sourced version, as I've used the old site version before.

**Comment by Jire** [comment]
Make sure you're using the latest 64-bit JDK; also make sure that you're not running Steam or CS:GO as admin. :smile:

**Comment by noobtra** [comment]
I have only the 64-bit JDK installed, CS:GO and Steam aren't running as admin as far as I know unfortunately.

**Comment by Jire** [comment]
Add me on Skype and we can arrange a TeamViewer session or something: **Jire..**
