### ISSUE TITLE
How do i change the settings if im not supposed to use the controller?(me again)

### ISSUE THREAD

**Issue by ElectrickFun** [Jire/Abendigo#61]
I saw that you closed my last thread without giving me a chance to respond back so i thank you for that now.
But now i ran into another problem:how to disable,change values(for example the smoothness of the auto aim)  if we cant use the controller?
Ive been changing things around in "Abendigo-master\Abendigo-master\src\main\kotlin\org\abendigo\plugin\csgo" but i cant seem to get them show ingame.For example ive disabled the ESP but it doesnt turn off in game.

**Comment by Jire** [comment]
After you make changes in the code you need to compile by using _build.bat_

Also, I'm sorry for closing the issue. If I'm correct, both the repository owner (i.e., me), and the issue creator should be able to reopen the issue.
