### ISSUE TITLE
Bug when editting

### ISSUE THREAD

**Issue by cra88y** [Jire/Abendigo#64]
Every once in a while I run into the issue: 
"Exception in thread "main" java.net.BindException: Address already in use: bind"
(in console)

When this error occurs the only way I can figure out to fix is to just delete all the files and rebuild. It happens even when using default code sometimes so I don't think its anything I've added myself... Any other fixes to this or something I'm doing wrong?

**Comment by davewolax** [comment]
What looks like is happening is that something is already running on port 8080 if you change the port number your problem should go away.

**Comment by cra88y** [comment]
File for port?

**Comment by cra88y** [comment]
I restarted my computer and it seemed to fix. Maybe just glitched IDK

**Comment by davewolax** [comment]
@cra88y great! sometimes restart will fix the problem
Could you please reply to my question in issue #55

**Comment by cra88y** [comment]
@davewolax Done :P
