### ISSUE TITLE
Bug while using deagle

### ISSUE THREAD

**Issue by punkjj** [Jire/Abendigo#7]
When 2 enemies are in our sight , I shoot at one of them the crosshair automatic goes to other one and lags a lot , Shakes a lot .. I Found this in deagle only .. Should I replace the aimassist plugin to old one ?

**Comment by punkjj** [comment]
Its happening with every weapon :cry:  The aim shakes a lot and goes to another player sometimes to our team player :sob:

**Comment by Jire** [comment]
@punkjj The aim and spray plugins were not touched. Check to be sure you aren't running multiple drivers at once.

**Comment by punkjj** [comment]
@Jire Im not using multiple drivers only one and Now I replaced the old plugins and this time it doesn't lag .. Controller is also working BTW Triggerbot For shotgun ? I researched a  little :P and found we have to replace Weapon id something can you add that plugin please ?

**Comment by punkjj** [comment]
This cheat doesn't work on servers protected by EAC (EasyAntiCheat)

**Comment by Jire** [comment]
Please open up new issues for each topic.

**Comment by punkjj** [comment]
Everything sorted out ! man.. You know you are awesome ! :hatsoff:
