### ISSUE TITLE
Build Fail

### ISSUE THREAD

**Issue by ogges** [Jire/Abendigo#71]
Hello,
i get a fail by compiling via run.bat

![abendigo](https://cloud.githubusercontent.com/assets/17764774/18780224/c6a578e4-817c-11e6-828f-131a449a211c.jpg)

Any Ideas? 
Where is the Log?

Tanks,
ogges

**Comment by davewolax** [comment]
1. Uninstall any current Java on your system from the control panel.
2. Download Latest JAVA SDK (Kit 8u102)
3. Restart system
4. Launch "run.bat" once again and wait for results.

**Comment by ogges** [comment]
didnt work. but i found the misstake.  Thanks
