### ISSUE TITLE
 (f9 to hide) 

### ISSUE THREAD

**Issue by marcofking1** [Jire/Abendigo#75]
i see the ( abendigo (f9 to hide) but i can't toggle any hacks..help pls

https://gyazo.com/5bea2abdc4ab7fa7c3eb1ac8c3a44728

**Comment by Jire** [comment]
The driver must be running and fully operational before you can run the controller.

**Comment by marcofking1** [comment]
how?

**Comment by marcofking1** [comment]
https://gyazo.com/30f4c89ecc4da8788c64f747dbf2f55f

**Comment by marcofking1** [comment]
can you do a full video of how to download/use the hack pls?
