### ISSUE TITLE
Skin changer for knife?

### ISSUE THREAD

**Issue by jo77528** [Jire/Abendigo#78]
so i went onto the website with all the skin codes to enter into IntelliJ but its not working for me? anyone can guide me what to do?

**Comment by bradylangdale** [comment]
You need to also change the knife model or have that knife model.

**Comment by bradylangdale** [comment]
Like for an AWP skin its only visible on an AWP same goes with knives.

**Comment by jo77528** [comment]
how do I change the knife model? can someone send me a code for it?

**Comment by Jire** [comment]
Not an available feature yet, sorry.
