### ISSUE TITLE
Cheat Doesn't Work on EAC (EasyAntiCheat)

### ISSUE THREAD

**Issue by punkjj** [Jire/Abendigo#8]
There's a app called SoStronk.. Its a gaming platform we can connect to its servers and play .. but we have to install EasyAntiCheat onto our systems (It is needed to play on the servers) The Anticheat gets injected into the game .. when I run abendigo nothing happens :sob:

**Comment by Jire** [comment]
Abendigo is only a matchmaking cheat, there are no plans to support different anti-cheats.
