### ISSUE TITLE
FOV aim not working :(

### ISSUE THREAD

**Issue by jo77528** [Jire/Abendigo#82]
hey guys Ive been trying to make the FOVaim to be headshot only...can someone gives me steps on how to do this? :) 

PS. should I use FOV aim or Aim assist plugin?

**Comment by Jire** [comment]
Replaced this line https://github.com/Jire/Abendigo/blob/master/src/main/kotlin/org/abendigo/plugin/csgo/FOVAimPlugin.kt#L32

with `private val TARGET_BONES = arrayOf(Bones.HEAD)`
