### ISSUE TITLE
Bug with aim assist

### ISSUE THREAD

**Issue by Dazee** [Jire/Abendigo#9]
There's a bug where when using aim assist when you are shooting the enemy and you get aim punched  the aim assist pulls the cross-hair down by a lot which is really weird.

**Comment by Jire** [comment]
I'll try to replicate and see what I can do.

**Comment by punkjj** [comment]
@Dazee Dont run Controller ... Just the "Abendigo-Master" it wont happen

**Comment by Dazee** [comment]
Is it possible to build this in linux and run it or do i have to make some adjustments  to the code ? im on Debian 8 jessie (i mean the  abendigoo

**Comment by Jire** [comment]
@Dazee You can build it on Linux but you need to either manually set offsets or find their patterns and change the patterns in code.

**Comment by uhFocuz** [comment]
How might one go about finding Offsets to a processes memory?

**Comment by davewolax** [comment]
@Jire When I'm close to an enemy spraying with p90 or something and enemy jumps, the aim assist goes up and down like so obvious. everybody noticed it and said I'm hacker. I had to immediately leave the match before getting reported. lol

**Comment by Jire** [comment]
@davewolax If you make a new issue for this, I will fix it.

**Comment by Jire** [comment]
@uhFocuz I'm not experienced in the subject but [WasserEsser's "Understanding Pattern Scanning" thread](http://www.mpgh.net/forum/showthread.php?t=1094622) may help.

**Comment by Jire** [comment]
Fixed in commit https://github.com/Jire/Abendigo/commit/52411a97b859066e8fc6581b14ea521b446d6d94
