### ISSUE TITLE
Triggerbot problems

### ISSUE THREAD

**Issue by jo77528** [Jire/Abendigo#90]
Hey Jire! first I just wanna say I love what you've done with Abendigo and cant wait for your new developments. But an issue I've had is that the Triggerbot is extremely delayed. How do I change it to no delay?

**Comment by Jire** [comment]
Open `TriggerBotPlugin.kt` and set `LEGIT` to `false`. Remember after making any changes to the code you must recompile by running `build.bat` :smile:

**Comment by jo77528** [comment]
thanks Jire!
